version: "3.9"
services:
  backend:
    build:
      context: .
      dockerfile: ./docker/backend/Dockerfile
    command: bash -c "npm run build && npm run start"
    ports: 
      - "3000:3000"
    volumes:
      - ./backend:/app
    depends_on:
      - mysql
  mysql:
    image: mysql:8.0.28
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - mysql-data:/var/lib/mysql
  frontend:
    build: 
      context: .
      dockerfile: ./docker/frontend/Dockerfile
    ports:
      - "4500:3000"
    volumes:
      - ./frontend:/app
volumes:
  mysql-data:
